/**
 * Gallery and image data from fredericbenard.com
 * Generated by: npm run scrape
 */

import galleriesEnData from "./galleries.en.json";
import galleriesFrData from "./galleries.fr.json";

export interface GalleryImage {
  id: string;
  url: string;
  caption?: string;
  sensitive?: {
    type: string;
  };
}

export interface Gallery {
  id: string;
  name: string;
  description: string;
  era: string;
  images: GalleryImage[];
}

export type GalleryLocale = "en" | "fr";

export function getGalleries(locale: GalleryLocale): Gallery[] {
  return (locale === "fr" ? galleriesFrData : galleriesEnData).galleries;
}

/** Backward-compatible default export used by older imports. */
export const GALLERIES: Gallery[] = getGalleries("en");
